let scene = document.querySelector('a-scene')
        let model = document.createElement('a-entity')
        model.setAttribute('scale', `2 2 2`)
        model.setAttribute('name', 'ensaama cour')
        model.setAttribute('gps-entity-place', `latitude: 48.833342; longitude: 2.295328;`)
        model.setAttribute('gltf-model', './assets/Flamingo.glb')
        model.setAttribute('animation-mixer', '')
        scene.appendChild(model)
